# Generated by Django 3.0 on 2019-12-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('place', models.CharField(max_length=40)),
                ('organizator', models.CharField(max_length=80)),
                ('eventLink', models.CharField(max_length=1350)),
                ('image1', models.CharField(max_length=1350)),
                ('image2', models.CharField(max_length=1350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('topic', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('image1', models.CharField(max_length=1350)),
                ('image2', models.CharField(max_length=1350, null=True)),
                ('publishDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('lesson', models.CharField(max_length=40)),
                ('topic', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=1350, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('topic', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('publishDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=10)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('stock', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=1350)),
            ],
        ),
        migrations.CreateModel(
            name='shuttleHours',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.IntegerField(primary_key=True, serialize=False)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
