# Generated by Django 3.0 on 2019-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191218_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
