# Generated by Django 3.0 on 2019-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191218_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
