# Generated by Django 3.0 on 2019-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191218_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.AlterField(
            model_name='news',
            name='publishDate',
            field=models.DateTimeField(null=True),
        ),
    ]
