# Generated by Django 3.0 on 2019-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='totalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
