# Generated by Django 3.0 on 2019-12-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191224_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchaseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
