# Generated by Django 3.0 on 2019-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191224_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='id',
        ),
        migrations.AddField(
            model_name='reply',
            name='replyId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
