# Generated by Django 3.0 on 2019-12-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191224_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
