# Generated by Django 3.0 on 2019-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventLink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image2',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
