# Generated by Django 3.0 on 2019-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191226_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizator',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=40),
        ),
    ]
