# Generated by Django 3.0 on 2019-12-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20191226_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('announcements', 'Announcements'), ('complaints', 'Complaints')], default='type', max_length=29),
        ),
    ]
