# Generated by Django 3.0 on 2019-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=29),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2xl', '2XL'), ('xl', 'XL'), ('l', 'L'), ('m', 'M'), ('s', 'S'), ('xs', 'XS')], default='2xl', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('trousers', 'Trousers'), ('shoes', 'Shoes'), ('Hoodies', 'Hoodies')], default='shirts', max_length=50),
        ),
    ]
