# Generated by Django 3.0 on 2020-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191226_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=29),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(choices=[('comp', 'Computer Engineering'), ('elec', 'Electric Engineering'), ('psyc', 'Psychology'), ('Architecture', 'Architecture'), ('ind', 'Industrial Engineering'), ('civil', 'Civil Engineering')], default='comp', max_length=29),
        ),
    ]
