# Generated by Django 3.0 on 2020-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200101_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlehours',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
