# Generated by Django 3.0 on 2020-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200103_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlehours',
            name='hour',
            field=models.TextField(null=True),
        ),
    ]
