# Generated by Django 3.0 on 2020-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlehours',
            name='hour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
