# Generated by Django 3.0 on 2020-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlehours',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
