# Generated by Django 3.0 on 2020-01-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200104_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
