# Generated by Django 3.0 on 2020-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson', models.CharField(max_length=40)),
                ('topic', models.CharField(max_length=40)),
                ('location', models.FileField(max_length=1350, upload_to='')),
            ],
        ),
    ]
