# Generated by Django 3.0 on 2020-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='male', max_length=29),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Psychology', 'Psychology'), ('Architecture', 'Architecture'), ('Industrial Engineering', 'Industrial Engineering'), ('Civil Engineering', 'Civil Engineering')], default='comp', max_length=29),
        ),
    ]
