# Generated by Django 3.0 on 2020-01-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200112_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='location',
            new_name='note',
        ),
    ]
